module.exports = [
  {
    id: "1001",
    g_image1: "defaults/default-placeholder",
    g_image2: "defaults/default-placeholder",
    g_image3: "defaults/default-placeholder",
    g_image4: "defaults/default-placeholder",
    g_image5: "defaults/default-placeholder",
    g_image6: "defaults/default-placeholder",
    g_image7: "defaults/default-placeholder",
    g_image8: "defaults/default-placeholder",
    profile_id: "101",
  },
  {
    id: "1002",
    g_image1: "defaults/default-placeholder",
    g_image2: "defaults/default-placeholder",
    g_image3: "defaults/default-placeholder",
    g_image4: "defaults/default-placeholder",
    g_image5: "defaults/default-placeholder",
    g_image6: "defaults/default-placeholder",
    g_image7: "defaults/default-placeholder",
    g_image8: "defaults/default-placeholder",
    profile_id: "102",
  },
  {
    id: "1003",
    g_image1: "defaults/default-placeholder",
    g_image2: "defaults/default-placeholder",
    g_image3: "defaults/default-placeholder",
    g_image4: "defaults/default-placeholder",
    g_image5: "defaults/default-placeholder",
    g_image6: "defaults/default-placeholder",
    g_image7: "defaults/default-placeholder",
    g_image8: "defaults/default-placeholder",
    profile_id: "103",
  },
  {
    id: "1004",
    g_image1: "defaults/default-placeholder",
    g_image2: "defaults/default-placeholder",
    g_image3: "defaults/default-placeholder",
    g_image4: "defaults/default-placeholder",
    g_image5: "defaults/default-placeholder",
    g_image6: "defaults/default-placeholder",
    g_image7: "defaults/default-placeholder",
    g_image8: "defaults/default-placeholder",
    profile_id: "104",
  },
  {
    id: "1005",
    g_image1: "defaults/default-placeholder",
    g_image2: "defaults/default-placeholder",
    g_image3: "defaults/default-placeholder",
    g_image4: "defaults/default-placeholder",
    g_image5: "defaults/default-placeholder",
    g_image6: "defaults/default-placeholder",
    g_image7: "defaults/default-placeholder",
    g_image8: "defaults/default-placeholder",
    profile_id: "105",
  },
];
