module.exports = [
  {
    id: "1001",
    g_image1: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image2: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image3: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image4: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image5: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image6: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image7: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image8: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    profile_id: "101",
  },
  {
    id: "1002",
    g_image1: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image2: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image3: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image4: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image5: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image6: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image7: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image8: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    profile_id: "102",
  },
  {
    id: "1003",
    g_image1: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image2: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image3: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image4: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image5: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image6: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image7: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image8: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    profile_id: "103",
  },
  {
    id: "1004",
    g_image1: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image2: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image3: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image4: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image5: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image6: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image7: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image8: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    profile_id: "104",
  },
  {
    id: "1005",
    g_image1: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image2: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image3: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image4: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image5: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image6: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image7: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    g_image8: "https://i.ibb.co/MZW1DHJ/gallery-image-sample.jpg",
    profile_id: "105",
  },
];
