module.exports = [
  {
    id: "1001",
    ic_title1: "Lorem ipsum dolor sit amet",
    ic_link1: "https://example.com",
    ic_image1: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    ic_title2: "Lorem ipsum dolor sit amet",
    ic_link2: "https://example.com",
    ic_image2: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    ic_title3: "Lorem ipsum dolor sit amet",
    ic_link3: "https://example.com",
    ic_image3: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    ic_title4: "Lorem ipsum dolor sit amet",
    ic_link4: "https://example.com",
    ic_image4: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    profile_id: "101",
  },
  {
    id: "1002",
    ic_title1: "Consectetur adipiscing elit",
    ic_link1: "https://example.com",
    ic_image1: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    ic_title2: "Consectetur adipiscing elit",
    ic_link2: "https://example.com",
    ic_image2: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    ic_title3: "Consectetur adipiscing elit",
    ic_link3: "https://example.com",
    ic_image3: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    ic_title4: "Consectetur adipiscing elit",
    ic_link4: "https://example.com",
    ic_image4: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    profile_id: "102",
  },
  {
    id: "1003",
    ic_title1: "Sed do eiusmod tempor incididunt",
    ic_link1: "https://example.com",
    ic_image1: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    ic_title2: "Sed do eiusmod tempor incididunt",
    ic_link2: "https://example.com",
    ic_image2: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    ic_title3: "Sed do eiusmod tempor incididunt",
    ic_link3: "https://example.com",
    ic_image3: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    ic_title4: "Sed do eiusmod tempor incididunt",
    ic_link4: "https://example.com",
    ic_image4: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    profile_id: "103",
  },
  {
    id: "1004",
    ic_title1: "Ut labore et dolore magna aliqua",
    ic_link1: "https://example.com",
    ic_image1: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    ic_title2: "Ut labore et dolore magna aliqua",
    ic_link2: "https://example.com",
    ic_image2: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    ic_title3: "Ut labore et dolore magna aliqua",
    ic_link3: "https://example.com",
    ic_image3: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    ic_title4: "Ut labore et dolore magna aliqua",
    ic_link4: "https://example.com",
    ic_image4: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    profile_id: "104",
  },
  {
    id: "1005",
    ic_title1: "Excepteur sint occaecat cupidatat non proident",
    ic_link1: "https://example.com",
    ic_image1: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    ic_title2: "Excepteur sint occaecat cupidatat non proident",
    ic_link2: "https://example.com",
    ic_image2: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    ic_title3: "Excepteur sint occaecat cupidatat non proident",
    ic_link3: "https://example.com",
    ic_image3: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    ic_title4: "Excepteur sint occaecat cupidatat non proident",
    ic_link4: "https://example.com",
    ic_image4: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    profile_id: "105",
  },
];
