module.exports = [
  {
    id: "1001",
    title1: "Lorem ipsum dolor sit amet",
    link1: "https://example.com",
    image1: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    title2: "Lorem ipsum dolor sit amet",
    link2: "https://example.com",
    image2: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    title3: "Lorem ipsum dolor sit amet",
    link3: "https://example.com",
    image3: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    title4: "Lorem ipsum dolor sit amet",
    link4: "https://example.com",
    image4: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    profile_id: "101",
  },
  {
    id: "1002",
    title1: "Consectetur adipiscing elit",
    link1: "https://example.com",
    image1: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    title2: "Consectetur adipiscing elit",
    link2: "https://example.com",
    image2: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    title3: "Consectetur adipiscing elit",
    link3: "https://example.com",
    image3: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    title4: "Consectetur adipiscing elit",
    link4: "https://example.com",
    image4: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    profile_id: "102",
  },
  {
    id: "1003",
    title1: "Sed do eiusmod tempor incididunt",
    link1: "https://example.com",
    image1: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    title2: "Sed do eiusmod tempor incididunt",
    link2: "https://example.com",
    image2: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    title3: "Sed do eiusmod tempor incididunt",
    link3: "https://example.com",
    image3: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    title4: "Sed do eiusmod tempor incididunt",
    link4: "https://example.com",
    image4: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    profile_id: "103",
  },
  {
    id: "1004",
    title1: "Ut labore et dolore magna aliqua",
    link1: "https://example.com",
    image1: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    title2: "Ut labore et dolore magna aliqua",
    link2: "https://example.com",
    image2: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    title3: "Ut labore et dolore magna aliqua",
    link3: "https://example.com",
    image3: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    title4: "Ut labore et dolore magna aliqua",
    link4: "https://example.com",
    image4: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    profile_id: "104",
  },
  {
    id: "1005",
    title1: "Excepteur sint occaecat cupidatat non proident",
    link1: "https://example.com",
    image1: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    title2: "Excepteur sint occaecat cupidatat non proident",
    link2: "https://example.com",
    image2: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    title3: "Excepteur sint occaecat cupidatat non proident",
    link3: "https://example.com",
    image3: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    title4: "Excepteur sint occaecat cupidatat non proident",
    link4: "https://example.com",
    image4: "https://i.ibb.co/VJwzt5C/image-card-sample.jpg",
    profile_id: "105",
  },
];
