module.exports = [
  {
    id: "1001",
    ext_title1: "01 Lorem ipsum dolor sit amet",
    ext_link1: "https://example.com",
    ext_title2: "02 Lorem ipsum dolor sit amet",
    ext_link2: "https://example.com",
    ext_title3: "03 Lorem ipsum dolor sit amet",
    ext_link3: "https://example.com",
    ext_title4: "04 Lorem ipsum dolor sit amet",
    ext_link4: "https://example.com",
    profile_id: "101",
  },
  {
    id: "1002",
    ext_title1: "01 Lorem ipsum dolor sit amet",
    ext_link1: "https://example.com",
    ext_title2: "02 Lorem ipsum dolor sit amet",
    ext_link2: "https://example.com",
    ext_title3: "03 Lorem ipsum dolor sit amet",
    ext_link3: "https://example.com",
    ext_title4: "04 Lorem ipsum dolor sit amet",
    ext_link4: "https://example.com",
    profile_id: "102",
  },
  {
    id: "1003",
    ext_title1: "01 Lorem ipsum dolor sit amet",
    ext_link1: "https://example.com",
    ext_title2: "02 Lorem ipsum dolor sit amet",
    ext_link2: "https://example.com",
    ext_title3: "03 Lorem ipsum dolor sit amet",
    ext_link3: "https://example.com",
    ext_title4: "04 Lorem ipsum dolor sit amet",
    ext_link4: "https://example.com",
    profile_id: "103",
  },
  {
    id: "1004",
    ext_title1: "01 Lorem ipsum dolor sit amet",
    ext_link1: "https://example.com",
    ext_title2: "02 Lorem ipsum dolor sit amet",
    ext_link2: "https://example.com",
    ext_title3: "03 Lorem ipsum dolor sit amet",
    ext_link3: "https://example.com",
    ext_title4: "04 Lorem ipsum dolor sit amet",
    ext_link4: "https://example.com",
    profile_id: "104",
  },
  {
    id: "1005",
    ext_title1: "01 Lorem ipsum dolor sit amet",
    ext_link1: "https://example.com",
    ext_title2: "02 Lorem ipsum dolor sit amet",
    ext_link2: "https://example.com",
    ext_title3: "03 Lorem ipsum dolor sit amet",
    ext_link3: "https://example.com",
    ext_title4: "04 Lorem ipsum dolor sit amet",
    ext_link4: "https://example.com",
    profile_id: "105",
  },
];
