module.exports = [
  {
    id: "1001",
    twitter: "https://twitter.com/",
    facebook: "https://www.facebook.com/",
    linkedin: "https://www.linkedin.com/",
    instagram: "https://www.instagram.com/",
    youtube: "https://www.youtube.com/",
    github: "https://github.com/",
    email: "mailto:example@email.com",
    profile_id: "101",
  },
  {
    id: "1002",
    twitter: "https://twitter.com/",
    facebook: "https://www.facebook.com/",
    linkedin: "https://www.linkedin.com/",
    instagram: "https://www.instagram.com/",
    youtube: "https://www.youtube.com/",
    github: "https://github.com/",
    email: "mailto:example@email.com",
    profile_id: "102",
  },
  {
    id: "1003",
    twitter: "https://twitter.com/",
    facebook: "https://www.facebook.com/",
    linkedin: "https://www.linkedin.com/",
    instagram: "https://www.instagram.com/",
    youtube: "https://www.youtube.com/",
    github: "https://github.com/",
    email: "mailto:example@email.com",
    profile_id: "103",
  },
  {
    id: "1004",
    twitter: "https://twitter.com/",
    facebook: "https://www.facebook.com/",
    linkedin: "https://www.linkedin.com/",
    instagram: "https://www.instagram.com/",
    youtube: "https://www.youtube.com/",
    github: "https://github.com/",
    email: "mailto:example@email.com",
    profile_id: "104",
  },
  {
    id: "1005",
    twitter: "https://twitter.com/",
    facebook: "https://www.facebook.com/",
    linkedin: "https://www.linkedin.com/",
    instagram: "https://www.instagram.com/",
    youtube: "https://www.youtube.com/",
    github: "https://github.com/",
    email: "mailto:example@email.com",
    profile_id: "105",
  },
];
